#################
# PET
#################

### 
GET /pet HTTP/1.1
Host: localhost:8001

### 
GET /pet/62091ef1525f0b001349c511 HTTP/1.1
Host: localhost:8001

###
POST /pet HTTP/1.1
Host: localhost:8001
Content-Type: application/json

{
    "name": "POST_TEST",
    "status": "AVAILABLE",
    "photos": [
        "POST_TEST@TEST.TEST",
        "POST_TEST@TEST.TEST",
        "POST_TEST@TEST.TEST"
    ],
    "category": {
        "id": 0,
        "name": "POST_TEST"
    },
    "tags": [
        {
            "id": 0,
            "name": "POST_TEST"
        },
        {
            "id": 1,
            "name": "POST_TEST"
        },
        {
            "id": 2,
            "name": "POST_TEST"
        }
    ]
}

###
PUT /pet/62091ef1525f0b001349c511 HTTP/1.1
Host: localhost:8001
Content-Type: application/json

{
    "name": "PUT_TEST",
    "status": "AVAILABLE",
    "photos": [
        "PUT_TEST@TEST.TEST",
        "PUT_TEST@TEST.TEST",
        "PUT_TEST@TEST.TEST"
    ],
    "category": {
        "id": 0,
        "name": "PUT_TEST"
    },
    "tags": [
        {
            "id": 0,
            "name": "PUT_TEST"
        },
        {
            "id": 1,
            "name": "PUT_TEST"
        },
        {
            "id": 2,
            "name": "PUT_TEST"
        }
    ]
}

###
DELETE /pet/62091ef1525f0b001349c511 HTTP/1.1
Host: localhost:8001
Content-Type: application/json

#################
# STORE
#################

### 
GET /store HTTP/1.1
Host: localhost:8002

#################
# USER
#################

### 
GET /user HTTP/1.1
Host: localhost:8003